#!/bin/sh

#set the location of the list of index names, a file with an index name per new line.
LIST_FILE="/tmp/idxlist.txt"

#set the location of the outputfile/name.
IDX_FILE="/tmp/indexes.conf"

  echo "Starting."
  echo "#indexes.conf generated by script" >> $IDX_FILE
  for DST in `cat "$LIST_FILE"`; do
    if [ -z "$DST" ]; then
      continue;
    fi
    echo "[$DST]" >> $IDX_FILE
    echo "homePath   = volume:primary/$DST""db/db" >> $IDX_FILE
    echo "coldPath   = volume:primary/$DST""db/colddb" >> $IDX_FILE
    echo "thawedPath = \$SPLUNK_DB/$DST""db/thaweddb" >> $IDX_FILE
    echo >> $IDX_FILE
    echo "[$DST] created"  
  done  
  echo "---------------------------"
  echo "Finished"
